# Generated by Django 5.2.7 on 2025-10-12 20:05

import src.apps.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Correo Electronico')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('wallet_addres', src.apps.common.fields.WalletAddressField(blank=True, max_length=42, null=True, verbose_name='Wallet')),
                ('user_active', models.BooleanField(default=True, verbose_name='Usuario Activo')),
                ('user_admin', models.BooleanField(default=False, verbose_name='Usuario administrador')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
