# Generated by Django 5.2.7 on 2025-10-12 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='wallet_addres',
            new_name='wallet_address',
        ),
    ]
