# Generated by Django 5.2.7 on 2025-10-14 00:25

import src.apps.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_wallet_addres_user_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=src.apps.common.fields.WalletAddressField(blank=True, max_length=42, null=True, unique=True, verbose_name='Wallet'),
        ),
    ]
