# Generated by Django 5.2.7 on 2025-10-20 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion del producto')),
                ('price', models.DecimalField(decimal_places=0, max_digits=38)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('listed', 'Listed'), ('sold', 'Sold'), ('cancelled', 'Cancelled')], default='listed', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_bought', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_selling', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
