# Generated by Django 5.2.7 on 2025-10-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productmodel_buyer_productmodel_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=38),
        ),
    ]
